#!/bin/sh

#Universal config, theoretically for all shells, but tested only on Bash and ZSH

export EDITOR="nvim"
export VISUAL="nvim"
function vim() {
    nvim "$@"
}

# Tmuxifier Layouts
export TMUXIFIER_LAYOUT_PATH=~/dotfiles/tmux/layouts

# Tmux path
#PATH+=":$HOME/dotfiles/shells/plugins/tmuxifier/bin"
#eval "$(tmuxifier init -)"

#export MANPAGER="export VIM_TINY=1; /bin/sh -c \"col -b | vim -c 'set ft=man ts=8 nomod nolist nonu noma' -c 'nnoremap q <Nop>' -c 'nnoremap q :q!<Enter>' -\""

# Language & Locale Settings, for crappy environments
if [[ -z "${LANG}" ]]; then
  if [ -f /etc/redhat-release ]; then
    # Thanks Redhat!
    export LANG='en_US.utf8'
  else
    export LANG='en_US.UTF-8'
  fi
fi

if [[ -z "${LC_ALL}" ]]; then
  if [ -f /etc/redhat-release ]; then
    # Thanks Redhat!
    export LC_ALL='en_US.utf8'
  else
    export LC_ALL='en_US.UTF-8'
  fi
fi

if [ -n "$TMUX" ]; then
  refresh_tmux() {
    local ssh_sock="$(tmux show-environment | grep "^SSH_AUTH_SOCK")"
    if [ ! -z "${ssh_sock}" ]; then
      export "${ssh_sock}"
    fi

    local display="$(tmux show-environment | grep "^DISPLAY")"
    if [ ! -z "${display}" ]; then
      export "${display}"
    fi
  }

else
  refresh_tmux() {
    return
  }
fi

source ${HOME}/dotfiles/shells/plugins/z/z.sh

export GOPATH="$HOME/go"

[ -f "/usr/local/opt/nvm/nvm.sh" ] && . /usr/local/opt/nvm/nvm.sh

# vim: set ft=sh :
