#!/bin/bash

#Universal config, theoretically for all shells, but tested only on Bash and ZSH

# Enable colours in BSD ls
export CLICOLOR=1

# Load the appropriate Prompt and LS COLORS
if [[ $TERM == *"256color"* ]]; then
    if [[ $ITERM_PROFILE == "Solarized Light" ]]; then
        if [[ -z "${RS_SKIP_AIRLINE}" ]]; then
            source ~/dotfiles/shells/airline/solarized.light
        fi
        source ~/dotfiles/shells/dircolors/solarized.ansi-light
    else
        if [[ -z "${RS_SKIP_AIRLINE}" ]]; then
            source ~/dotfiles/shells/airline/solarized.dark
        fi
        source ~/dotfiles/shells/dircolors/solarized.ansi-dark
    fi
else
    source ~/dotfiles/shells/dircolors/solarized.256dark
fi

# alias ls to use colors
# GNU LS
if ls --color -d . >/dev/null 2>&1; then
    LS_DEFAULT="ls --color=auto"

# BSD LS
elif ls -G -d . >/dev/null 2>&1; then
    LS_DEFAULT="ls -G"

else
    LS_DEFAULT="ls"
fi;

alias ls=${LS_DEFAULT}
alias ll="${LS_DEFAULT} -l"
alias la="${LS_DEFAULT} -al"
alias l=${LS_DEFAULT}

# genpass n
# where n is the number of bytes, try and generate a password up to n bytes
genpass() {
    if [ -n "$1" ]; then
        TEMP=`LC_ALL=C tr -dc 'a-zA-Z0-9-_!@#$%^&*()_+{}|:<>?=' < /dev/random | head -c "$1"`
        echo $TEMP
    else
        echo "need number of bytes"
    fi
}

# Given author name, calculate contributions in terms of line of change
gitcalc() {
    if [ -n "$1" ]; then
        git log --shortstat --author "$1" | grep "files\? changed" | awk '{files+=$1; inserted+=$4; deleted+=$6} END {print "files changed", files, "lines inserted:", inserted, "lines deleted:", deleted}'
    else
        echo "need author name"
    fi
}

alias bc='popd'
PATH="$HOME/.bin:$HOME/go/bin:${PATH}"
export STM32CubeMX_PATH=/Applications/STMicroelectronics/STM32CubeMX.app/Contents/Resources

# vim: set ft=sh :
# 

