#Editor
#export MANPAGER="export VIM_TINY=1; /bin/sh -c \"col -b | vim -c 'set ft=man ts=8 nomod nolist nonu noma' -c 'nnoremap q <Nop>' -c 'nnoremap q :q!<Enter>' -\""

# Arch linux
if [ -f "/etc/arch-release" ];
then
    true
# Mac OS X
elif [ `uname` = "Darwin" ]; then
    # /etc/profile
    ## system-wide environment settings for zsh(1)
    #if [ -x /usr/libexec/path_helper ]; then
    #        PATH=""
    #        MANPATH=""
    #        eval `/usr/libexec/path_helper -s`
    #fi

    if  [ -d "/usr/local/opt/coreutils/libexec/gnubin" ]; then
        PATH=/usr/local/opt/coreutils/libexec/gnubin:$PATH
        MANPATH="/usr/local/opt/coreutils/libexec/gnuman:${MANPATH}"
    fi

    if [ -d "$HOME/.cabal/bin" ]; then
        PATH=$HOME/.cabal/bin:$PATH
    fi

    if [ -d "$HOME/.cargo/bin" ]; then
        PATH=$HOME/.cargo/bin:$PATH
    fi

    if [ -d "$HOME/.bin" ]; then
        PATH=$HOME/.bin:$PATH
    fi
    PATH=/opt/homebrew/.bin:$PATH

    subl() {
        /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl
    }
fi

export MANPATH="${HOME}/dotfiles/shells/plugins/z/man:${MANPATH}"
export PATH

gopkgimports() {
    go list -f '{{ join .Imports "\n" }}' ${@}
}

# vim: set ft=zsh :
