
# Enable Antigen
source ~/.antigen-hs/antigen-hs/init.zsh

#autoload run-help
#HELPDIR=/usr/local/share/zsh/help

# Enable Superior Key bindings
#set -o vi

# Make the superior key bindings better
# Reduce delay
#export KEYTIMEOUT=1


# genpass n
# where n is the number of bytes, try and generate a password up to n bytes
genpass() {
    if [ -n "$1" ]; then
        TEMP=`LC_ALL=C tr -dc 'a-zA-Z0-9-_!@#$%^&*()_+{}|:<>?=' < /dev/random | head -c "$1"`
        echo $TEMP
    else
        echo "need number of bytes"
    fi
}

# Given author name, calculate contributions
gitcalc() {
    if [ -n "$1" ]; then
        git log --shortstat --author "$1" | grep "files\? changed" | awk '{files+=$1; inserted+=$4; deleted+=$6} END {print "files changed", files, "lines inserted:", inserted, "lines deleted:", deleted}'
    else
        echo "need author name"
    fi
}


# Set auto pushd
setopt AUTO_PUSHD

# Load the appropriate Prompt and LS COLORS

#ZSH Tab Completion Colors
zstyle ':completion:*' list-colors "${(@s.:.)LS_COLORS}"
#zstyle ':completion:*' matcher-list 'r:[[:ascii:]]||[[:ascii:]]=** r:|=* m:{a-z\-}={A-Z\_}'
#compinit

# History searching magic
# bind P and N for EMACS mode
# bindkey -M emacs '^P' history-substring-search-up
# bindkey -M emacs '^N' history-substring-search-down
#
# # bind k and j for VI mode
# bindkey -M vicmd 'k' history-substring-search-up
# bindkey -M vicmd 'j' history-substring-search-down
#
# # bind UP and DOWN arrow keys
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

setopt SHARE_HISTORY

SAVEHIST=1000

if (( ! EUID )); then
  HISTFILE=~/.history_root
else
  HISTFILE=~/.history
fi
export HISTFILE

autoload -Uz compinit
compinit
