#!/bin/bash

#Universal config, theoretically for all shells, but tested only on Bash and ZSH

# Load colours
if [[ $TERM == *"256color"* ]]; then
    if [[ $ITERM_PROFILE == "Solarized Light" ]]; then
        if [[ -z "${RS_SKIP_AIRLINE}" ]]; then
            source ~/dotfiles/shells/airline/solarized.light
        fi
        source ~/dotfiles/shells/dircolors/solarized.ansi-light
    else
        if [[ -z "${RS_SKIP_AIRLINE}" ]]; then
            source ~/dotfiles/shells/airline/solarized.dark
        fi
        source ~/dotfiles/shells/dircolors/solarized.ansi-dark
    fi
else
    source ~/dotfiles/shells/dircolors/solarized.256dark
fi

# alias ls to use colors
if ls --color -d . >/dev/null 2>&1; then
    # GNU LS
    LS_DEFAULT="ls --color=auto"
elif ls -G -d . >/dev/null 2>&1; then
    # BSD LS
    LS_DEFAULT="ls -G"
fi;

alias ls=${LS_DEFAULT}
alias ll="{$LS_DEFAULT} -l"
alias la="${LS_DEFAULT} -al"
alias l=${LS_DEFAULT}

# vim: set ft=sh
