#!/bin/sh

MOD=false
shopt -s dotglob
cd $HOME/dotfiles/dotbomb/

for f in *; do
    if [ "$(cat "$f" | openssl md5)" != "$(cat "$HOME/$f" | openssl md5)" ]; then
        MOD=true
        echo "$f modified \n"
    fi
done

if [ "$MOD" = true ]; then
    echo "\nWARNING!! The dotbombed configuration files have been modified."
    echo "Synchronise the changes between dotbomb, and the shellrcs"
    echo "then rerun the hook"
    exit 1;
fi
