#Editor
export EDITOR="vim"
export VISUAL="vim"
export MANPAGER="/bin/sh -c \"col -b | vim -c 'set ft=man ts=8 nomod nolist nonu noma' -c 'nnoremap q <Nop>' -c 'nnoremap q :q!<Enter>' -\""

# Language & Locale Settings
if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

if [[ -z "$LC_ALL" ]]; then
  export LC_ALL='en_US.UTF-8'
fi

# Arch linux
if [ -f "/etc/arch-release" ]; 
then
    true
# Mac OS X
elif [ `uname` = "Darwin" ]; then 
    # /etc/profile
    ## system-wide environment settings for zsh(1)
    if [ -x /usr/libexec/path_helper ]; then
            PATH=""
            export MANPATH=""
            eval `/usr/libexec/path_helper -s`
    fi

    if [ -d $(brew --prefix coreutils) ]; then
        PATH=/usr/local/opt/coreutils/libexec/gnubin:$(brew --prefix coreutils):$PATH
        export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
    fi

    if [ -d ~/.cabal/bin ]; then
        PATH=~/.cabal/bin:$PATH
    fi

    export PATH

    if [ -x "$(which pyenv)" ]; then  
        export PYENV_ROOT=/usr/local/opt/python
        eval "$(pyenv init -)"
    fi

fi

if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
