# Enable Antigen
source ~/.antigen-hs/antigen-hs/init.zsh

# Tmuxifier Layouts
export TMUXIFIER_LAYOUT_PATH=~/dotfiles/tmux/layouts

autoload run-help
HELPDIR=/usr/local/share/zsh/help

# Enable Superior Key bindings
set -o vi

# Make the superior key bindings better
# Reduce delay
export KEYTIMEOUT=1

# Enable some colours
export CLICOLOR=1

# genpass n
# where n is the number of bytes, try and generate a password up to n bytes.
genpass() {
    if [ $@ != "" ]; then
        TEMP=`LC_ALL=C tr -dc 'a-zA-Z0-9-_!@#$%^&*()_+{}|:<>?=' < /dev/random | head -c "$@"`
        echo $TEMP
    fi
}

# Enable tab completion
autoload -U compinit
compinit

# Set auto pushd
setopt AUTO_PUSHD

# Load the appropriate Prompt and LS COLORS
if [[ -z $ITERM_PROFILE ]]; then
    source ~/dotfiles/zsh/airline-dark
elif [[ $ITERM_PROFILE == "Solarized Dark" ]]; then
    source ~/dotfiles/zsh/airline-dark
elif [[ $ITERM_PROFILE == "Solarized Light" ]]; then
    source ~/dotfiles/zsh/airline-light
fi;

#ZSH Tab Completion Colors
zstyle ':completion:*' list-colors "${(@s.:.)LS_COLORS}"
autoload -Uz compinit
compinit

# LS Aliases
if ls --color -d . >/dev/null 2>&1; then
#GNU LS
    LS_DEFAULT="ls --color=auto"
elif ls -G -d . >/dev/null 2>&1; then
#BSD LS
    LS_DEFAULT="ls -G"
fi;

alias ls=$LS_DEFAULT
alias ll="$LS_DEFAULT -l"
alias la="$LS_DEFAULT -al"
