# Arch linux
if [ -f "/etc/arch-release" ]; 
then
    true
# Mac OS X
elif [ `uname` = "Darwin" ];
then 
    export LC_ALL=en_US.UTF-8
    export LANG=en_US.UTF-8
    export PATH="$(brew --prefix coreutils)/libexec/gnubin:~/.cabal/bin:$PATH"
fi

# Enable Antigen
source ~/.antigen-hs/antigen-hs/init.zsh

autoload run-help
HELPDIR=/usr/local/share/zsh/help

# Enable Superior Key bindings
set -o vi

# Make the superior key bindings better
# Reduce delay
export KEYTIMEOUT=1

# Enable some colours
export CLICOLOR=1

# genpass n
# where n is the number of bytes, try and generate a password up to n bytes.
genpass() {
    if [ $@ != "" ]; then
        TEMP=`LC_ALL=C tr -dc 'a-zA-Z0-9-_!@#$%^&*()_+{}|:<>?=' < /dev/random | head -c "$@"`
        echo $TEMP
    fi
}

# Enable tab completion
autoload -U compinit
compinit

# Set Editor
export EDITOR="vim"
export VISUAL="vim"

# Set auto pushd
setopt AUTO_PUSHD

# Get rid of that extra space on the right
ZLE_RPROMPT_INDENT=0

# Lighthouse function
it2_rot() {
    if [[ $ITERM_PROFILE == "Solarized Dark" ]]; then
        source ~/dotfiles/zsh/solar-dark
    elif [[ $ITERM_PROFILE == "Solarized Light" ]]; then
        source ~/dotfiles/zsh/solar-light
    fi;
}

if [[ -z $ITERM_PROFILE ]]; then
    source ~/dotfiles/zsh/airline-dark
elif [[ $ITERM_PROFILE == "Solarized Dark" ]]; then
    source ~/dotfiles/zsh/airline-dark
elif [[ $ITERM_PROFILE == "Solarized Light" ]]; then
    source ~/dotfiles/zsh/airline-light
fi;
